// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.36.0
// source: alert/v1/alert.proto

package alertv1

import (
	v1 "github.com/stockmafia/trading-app/proto/stockmafia/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWatchlistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWatchlistRequest) Reset() {
	*x = GetWatchlistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_v1_alert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWatchlistRequest) ProtoMessage() {}

func (x *GetWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_v1_alert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWatchlistRequest.ProtoReflect.Descriptor instead.
func (*GetWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_alert_v1_alert_proto_rawDescGZIP(), []int{0}
}

type GetWatchlistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stocks []*v1.Stock `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
}

func (x *GetWatchlistResponse) Reset() {
	*x = GetWatchlistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_v1_alert_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWatchlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWatchlistResponse) ProtoMessage() {}

func (x *GetWatchlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_v1_alert_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWatchlistResponse.ProtoReflect.Descriptor instead.
func (*GetWatchlistResponse) Descriptor() ([]byte, []int) {
	return file_alert_v1_alert_proto_rawDescGZIP(), []int{1}
}

func (x *GetWatchlistResponse) GetStocks() []*v1.Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type GetAlertsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAlertsRequest) Reset() {
	*x = GetAlertsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_v1_alert_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsRequest) ProtoMessage() {}

func (x *GetAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_v1_alert_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsRequest.ProtoReflect.Descriptor instead.
func (*GetAlertsRequest) Descriptor() ([]byte, []int) {
	return file_alert_v1_alert_proto_rawDescGZIP(), []int{2}
}

type GetAlertsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alerts []*v1.Alert `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
}

func (x *GetAlertsResponse) Reset() {
	*x = GetAlertsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_v1_alert_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsResponse) ProtoMessage() {}

func (x *GetAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_v1_alert_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsResponse.ProtoReflect.Descriptor instead.
func (*GetAlertsResponse) Descriptor() ([]byte, []int) {
	return file_alert_v1_alert_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlertsResponse) GetAlerts() []*v1.Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_alert_v1_alert_proto protoreflect.FileDescriptor

var file_alert_v1_alert_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6c, 0x65, 0x72, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66,
	0x69, 0x61, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x15, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x06,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x06, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x06, 0x61, 0x6c,
	0x65, 0x72, 0x74, 0x73, 0x32, 0xcf, 0x01, 0x0a, 0x0c, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x63, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66,
	0x69, 0x61, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x61, 0x6c, 0x65,
	0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x12, 0x25, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d,
	0x61, 0x66, 0x69, 0x61, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x61, 0x6c, 0x65, 0x72,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2f,
	0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2f, 0x61, 0x6c, 0x65,
	0x72, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alert_v1_alert_proto_rawDescOnce sync.Once
	file_alert_v1_alert_proto_rawDescData = file_alert_v1_alert_proto_rawDesc
)

func file_alert_v1_alert_proto_rawDescGZIP() []byte {
	file_alert_v1_alert_proto_rawDescOnce.Do(func() {
		file_alert_v1_alert_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_v1_alert_proto_rawDescData)
	})
	return file_alert_v1_alert_proto_rawDescData
}

var file_alert_v1_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_alert_v1_alert_proto_goTypes = []interface{}{
	(*GetWatchlistRequest)(nil),  // 0: stockmafia.alert.v1.GetWatchlistRequest
	(*GetWatchlistResponse)(nil), // 1: stockmafia.alert.v1.GetWatchlistResponse
	(*GetAlertsRequest)(nil),     // 2: stockmafia.alert.v1.GetAlertsRequest
	(*GetAlertsResponse)(nil),    // 3: stockmafia.alert.v1.GetAlertsResponse
	(*v1.Stock)(nil),             // 4: stockmafia.common.v1.Stock
	(*v1.Alert)(nil),             // 5: stockmafia.common.v1.Alert
}
var file_alert_v1_alert_proto_depIdxs = []int32{
	4, // 0: stockmafia.alert.v1.GetWatchlistResponse.stocks:type_name -> stockmafia.common.v1.Stock
	5, // 1: stockmafia.alert.v1.GetAlertsResponse.alerts:type_name -> stockmafia.common.v1.Alert
	0, // 2: stockmafia.alert.v1.AlertService.GetWatchlist:input_type -> stockmafia.alert.v1.GetWatchlistRequest
	2, // 3: stockmafia.alert.v1.AlertService.GetAlerts:input_type -> stockmafia.alert.v1.GetAlertsRequest
	1, // 4: stockmafia.alert.v1.AlertService.GetWatchlist:output_type -> stockmafia.alert.v1.GetWatchlistResponse
	3, // 5: stockmafia.alert.v1.AlertService.GetAlerts:output_type -> stockmafia.alert.v1.GetAlertsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alert_v1_alert_proto_init() }
func file_alert_v1_alert_proto_init() {
	if File_alert_v1_alert_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alert_v1_alert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWatchlistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_v1_alert_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWatchlistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_v1_alert_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlertsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_v1_alert_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlertsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_v1_alert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alert_v1_alert_proto_goTypes,
		DependencyIndexes: file_alert_v1_alert_proto_depIdxs,
		MessageInfos:      file_alert_v1_alert_proto_msgTypes,
	}.Build()
	File_alert_v1_alert_proto = out.File
	file_alert_v1_alert_proto_rawDesc = nil
	file_alert_v1_alert_proto_goTypes = nil
	file_alert_v1_alert_proto_depIdxs = nil
}
