export type Market = "IN" | "US";

export interface Instrument {
  symbol: string;
  yahoo: string;
  name: string;
  sector: string;
  market: Market;
  exchange: string;
  currency: "INR" | "USD";
}

export const INDIA_STOCKS: Instrument[] = [
  { symbol: "RELIANCE", yahoo: "RELIANCE.NS", name: "Reliance Industries", sector: "Energy", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "TCS", yahoo: "TCS.NS", name: "Tata Consultancy Services", sector: "IT", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "INFY", yahoo: "INFY.NS", name: "Infosys", sector: "IT", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "HDFCBANK", yahoo: "HDFCBANK.NS", name: "HDFC Bank", sector: "Banking", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "ICICIBANK", yahoo: "ICICIBANK.NS", name: "ICICI Bank", sector: "Banking", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "SBIN", yahoo: "SBIN.NS", name: "State Bank of India", sector: "Banking", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "BHARTIARTL", yahoo: "BHARTIARTL.NS", name: "Bharti Airtel", sector: "Telecom", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "ITC", yahoo: "ITC.NS", name: "ITC", sector: "FMCG", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "LT", yahoo: "LT.NS", name: "Larsen & Toubro", sector: "Infrastructure", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "AXISBANK", yahoo: "AXISBANK.NS", name: "Axis Bank", sector: "Banking", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "HINDUNILVR", yahoo: "HINDUNILVR.NS", name: "Hindustan Unilever", sector: "FMCG", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "MARUTI", yahoo: "MARUTI.NS", name: "Maruti Suzuki", sector: "Auto", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "TATAMOTORS", yahoo: "TATAMOTORS.NS", name: "Tata Motors", sector: "Auto", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "SUNPHARMA", yahoo: "SUNPHARMA.NS", name: "Sun Pharma", sector: "Pharma", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "WIPRO", yahoo: "WIPRO.NS", name: "Wipro", sector: "IT", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "KOTAKBANK", yahoo: "KOTAKBANK.NS", name: "Kotak Mahindra Bank", sector: "Banking", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "BAJFINANCE", yahoo: "BAJFINANCE.NS", name: "Bajaj Finance", sector: "NBFC", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "ASIANPAINT", yahoo: "ASIANPAINT.NS", name: "Asian Paints", sector: "Materials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "TITAN", yahoo: "TITAN.NS", name: "Titan Company", sector: "Consumer", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "ULTRACEMCO", yahoo: "ULTRACEMCO.NS", name: "UltraTech Cement", sector: "Cement", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "NTPC", yahoo: "NTPC.NS", name: "NTPC", sector: "Energy", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "POWERGRID", yahoo: "POWERGRID.NS", name: "Power Grid Corp", sector: "Energy", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "ONGC", yahoo: "ONGC.NS", name: "Oil & Natural Gas Corp", sector: "Energy", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "TATACONSUM", yahoo: "TATACONSUM.NS", name: "Tata Consumer Products", sector: "FMCG", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "ADANIENT", yahoo: "ADANIENT.NS", name: "Adani Enterprises", sector: "Conglomerate", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "ADANIPORTS", yahoo: "ADANIPORTS.NS", name: "Adani Ports", sector: "Infrastructure", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "JSWSTEEL", yahoo: "JSWSTEEL.NS", name: "JSW Steel", sector: "Materials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "TATASTEEL", yahoo: "TATASTEEL.NS", name: "Tata Steel", sector: "Materials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "HCLTECH", yahoo: "HCLTECH.NS", name: "HCL Technologies", sector: "IT", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "TECHM", yahoo: "TECHM.NS", name: "Tech Mahindra", sector: "IT", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "BAJAJFINSV", yahoo: "BAJAJFINSV.NS", name: "Bajaj Finserv", sector: "NBFC", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "COALINDIA", yahoo: "COALINDIA.NS", name: "Coal India", sector: "Mining", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "NESTLEIND", yahoo: "NESTLEIND.NS", name: "Nestle India", sector: "FMCG", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "BRITANNIA", yahoo: "BRITANNIA.NS", name: "Britannia Industries", sector: "FMCG", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "DIVISLAB", yahoo: "DIVISLAB.NS", name: "Divi's Laboratories", sector: "Pharma", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "DRREDDY", yahoo: "DRREDDY.NS", name: "Dr. Reddy's Laboratories", sector: "Pharma", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "CIPLA", yahoo: "CIPLA.NS", name: "Cipla", sector: "Pharma", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "EICHERMOT", yahoo: "EICHERMOT.NS", name: "Eicher Motors", sector: "Auto", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "HEROMOTOCO", yahoo: "HEROMOTOCO.NS", name: "Hero MotoCorp", sector: "Auto", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "BAJAJ-AUTO", yahoo: "BAJAJ-AUTO.NS", name: "Bajaj Auto", sector: "Auto", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "M&M", yahoo: "M&M.NS", name: "Mahindra & Mahindra", sector: "Auto", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "INDUSINDBK", yahoo: "INDUSINDBK.NS", name: "IndusInd Bank", sector: "Banking", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "GRASIM", yahoo: "GRASIM.NS", name: "Grasim Industries", sector: "Materials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "HINDALCO", yahoo: "HINDALCO.NS", name: "Hindalco Industries", sector: "Materials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "VEDL", yahoo: "VEDL.NS", name: "Vedanta", sector: "Materials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "DLF", yahoo: "DLF.NS", name: "DLF", sector: "Real Estate", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "APOLLOHOSP", yahoo: "APOLLOHOSP.NS", name: "Apollo Hospitals", sector: "Healthcare", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "TRENT", yahoo: "TRENT.NS", name: "Trent (Westside)", sector: "Consumer", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "ZOMATO", yahoo: "ZOMATO.NS", name: "Zomato", sector: "Technology", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "PAYTM", yahoo: "PAYTM.NS", name: "One97 Communications", sector: "Technology", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "POLYCAB", yahoo: "POLYCAB.NS", name: "Polycab India", sector: "Industrials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "DABUR", yahoo: "DABUR.NS", name: "Dabur India", sector: "FMCG", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "MARICO", yahoo: "MARICO.NS", name: "Marico", sector: "FMCG", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "COLPAL", yahoo: "COLPAL.NS", name: "Colgate-Palmolive India", sector: "FMCG", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "PIDILITIND", yahoo: "PIDILITIND.NS", name: "Pidilite Industries", sector: "Materials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "SIEMENS", yahoo: "SIEMENS.NS", name: "Siemens India", sector: "Industrials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "ABB", yahoo: "ABB.NS", name: "ABB India", sector: "Industrials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "BHEL", yahoo: "BHEL.NS", name: "Bharat Heavy Electricals", sector: "Industrials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "IRCTC", yahoo: "IRCTC.NS", name: "IRCTC", sector: "Consumer", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "LICI", yahoo: "LICI.NS", name: "Life Insurance Corp", sector: "Insurance", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "SBILIFE", yahoo: "SBILIFE.NS", name: "SBI Life Insurance", sector: "Insurance", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "HDFCLIFE", yahoo: "HDFCLIFE.NS", name: "HDFC Life Insurance", sector: "Insurance", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "ICICIPRULI", yahoo: "ICICIPRULI.NS", name: "ICICI Prudential Life", sector: "Insurance", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "LTIM", yahoo: "LTIM.NS", name: "LTIMindtree", sector: "IT", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "PERSISTENT", yahoo: "PERSISTENT.NS", name: "Persistent Systems", sector: "IT", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "COFORGE", yahoo: "COFORGE.NS", name: "Coforge", sector: "IT", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "MPHASIS", yahoo: "MPHASIS.NS", name: "Mphasis", sector: "IT", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "OBEROIRLTY", yahoo: "OBEROIRLTY.NS", name: "Oberoi Realty", sector: "Real Estate", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "GODREJPROP", yahoo: "GODREJPROP.NS", name: "Godrej Properties", sector: "Real Estate", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "ATUL", yahoo: "ATUL.NS", name: "Atul Ltd", sector: "Materials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "NAVINFLUOR", yahoo: "NAVINFLUOR.NS", name: "Navin Fluorine", sector: "Materials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "TATAELXSI", yahoo: "TATAELXSI.NS", name: "Tata Elxsi", sector: "IT", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "DEEPAKNTR", yahoo: "DEEPAKNTR.NS", name: "Deepak Nitrite", sector: "Materials", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "VOLTAS", yahoo: "VOLTAS.NS", name: "Voltas", sector: "Consumer", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "BALKRISIND", yahoo: "BALKRISIND.NS", name: "Balkrishna Industries", sector: "Auto", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "MRF", yahoo: "MRF.NS", name: "MRF", sector: "Auto", market: "IN", exchange: "NSE", currency: "INR" },
  { symbol: "AMARARAJA", yahoo: "AMARARAJA.NS", name: "Amara Raja Energy", sector: "Auto", market: "IN", exchange: "NSE", currency: "INR" },
];

export const US_STOCKS: Instrument[] = [
  { symbol: "AAPL", yahoo: "AAPL", name: "Apple", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "MSFT", yahoo: "MSFT", name: "Microsoft", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "NVDA", yahoo: "NVDA", name: "NVIDIA", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "GOOGL", yahoo: "GOOGL", name: "Alphabet", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "AMZN", yahoo: "AMZN", name: "Amazon", sector: "Consumer", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "META", yahoo: "META", name: "Meta Platforms", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "TSLA", yahoo: "TSLA", name: "Tesla", sector: "Auto", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "AVGO", yahoo: "AVGO", name: "Broadcom", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "JPM", yahoo: "JPM", name: "JPMorgan Chase", sector: "Banking", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "V", yahoo: "V", name: "Visa", sector: "Financials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "UNH", yahoo: "UNH", name: "UnitedHealth", sector: "Healthcare", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "XOM", yahoo: "XOM", name: "Exxon Mobil", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "JNJ", yahoo: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "WMT", yahoo: "WMT", name: "Walmart", sector: "Consumer", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "MA", yahoo: "MA", name: "Mastercard", sector: "Financials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "PG", yahoo: "PG", name: "Procter & Gamble", sector: "Consumer", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "HD", yahoo: "HD", name: "Home Depot", sector: "Consumer", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "COST", yahoo: "COST", name: "Costco", sector: "Consumer", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "NFLX", yahoo: "NFLX", name: "Netflix", sector: "Communication", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "AMD", yahoo: "AMD", name: "AMD", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "UBER", yahoo: "UBER", name: "Uber Technologies", sector: "Technology", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "CRM", yahoo: "CRM", name: "Salesforce", sector: "Technology", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "ADBE", yahoo: "ADBE", name: "Adobe", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "PYPL", yahoo: "PYPL", name: "PayPal", sector: "Financials", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "INTC", yahoo: "INTC", name: "Intel", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "CMCSA", yahoo: "CMCSA", name: "Comcast", sector: "Communication", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "PEP", yahoo: "PEP", name: "PepsiCo", sector: "Consumer", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "CSCO", yahoo: "CSCO", name: "Cisco Systems", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "TMO", yahoo: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "ABT", yahoo: "ABT", name: "Abbott Laboratories", sector: "Healthcare", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "NKE", yahoo: "NKE", name: "Nike", sector: "Consumer", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "ORCL", yahoo: "ORCL", name: "Oracle", sector: "Technology", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "QCOM", yahoo: "QCOM", name: "Qualcomm", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "TXN", yahoo: "TXN", name: "Texas Instruments", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "PM", yahoo: "PM", name: "Philip Morris International", sector: "Consumer", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "UPS", yahoo: "UPS", name: "United Parcel Service", sector: "Industrials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "MS", yahoo: "MS", name: "Morgan Stanley", sector: "Banking", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "GS", yahoo: "GS", name: "Goldman Sachs", sector: "Banking", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "BABA", yahoo: "BABA", name: "Alibaba", sector: "Technology", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "SNOW", yahoo: "SNOW", name: "Snowflake", sector: "Technology", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "PLTR", yahoo: "PLTR", name: "Palantir Technologies", sector: "Technology", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "COIN", yahoo: "COIN", name: "Coinbase Global", sector: "Financials", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "SHOP", yahoo: "SHOP", name: "Shopify", sector: "Technology", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "NET", yahoo: "NET", name: "Cloudflare", sector: "Technology", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "DDOG", yahoo: "DDOG", name: "Datadog", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "ZS", yahoo: "ZS", name: "Zscaler", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "CRWD", yahoo: "CRWD", name: "CrowdStrike", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "MARA", yahoo: "MARA", name: "Marathon Digital Holdings", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "RIVN", yahoo: "RIVN", name: "Rivian Automotive", sector: "Auto", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "CAT", yahoo: "CAT", name: "Caterpillar", sector: "Industrials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "RTX", yahoo: "RTX", name: "RTX Corp", sector: "Industrials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "NOW", yahoo: "NOW", name: "ServiceNow", sector: "Technology", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "AMGN", yahoo: "AMGN", name: "Amgen", sector: "Healthcare", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "IBM", yahoo: "IBM", name: "IBM", sector: "Technology", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "GE", yahoo: "GE", name: "GE Aerospace", sector: "Industrials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "BA", yahoo: "BA", name: "Boeing", sector: "Industrials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "BLK", yahoo: "BLK", name: "BlackRock", sector: "Financials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "SPGI", yahoo: "SPGI", name: "S&P Global", sector: "Financials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "AXP", yahoo: "AXP", name: "American Express", sector: "Financials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "CVX", yahoo: "CVX", name: "Chevron", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "LLY", yahoo: "LLY", name: "Eli Lilly", sector: "Healthcare", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "MDT", yahoo: "MDT", name: "Medtronic", sector: "Healthcare", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "GILD", yahoo: "GILD", name: "Gilead Sciences", sector: "Healthcare", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "ISRG", yahoo: "ISRG", name: "Intuitive Surgical", sector: "Healthcare", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "BKNG", yahoo: "BKNG", name: "Booking Holdings", sector: "Consumer", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "LULU", yahoo: "LULU", name: "Lululemon", sector: "Consumer", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "SBUX", yahoo: "SBUX", name: "Starbucks", sector: "Consumer", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "MCD", yahoo: "MCD", name: "McDonald's", sector: "Consumer", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "TGT", yahoo: "TGT", name: "Target", sector: "Consumer", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "LOW", yahoo: "LOW", name: "Lowe's", sector: "Consumer", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "ADP", yahoo: "ADP", name: "ADP", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "REGN", yahoo: "REGN", name: "Regeneron", sector: "Healthcare", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "VRTX", yahoo: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "DE", yahoo: "DE", name: "Deere & Co", sector: "Industrials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "CI", yahoo: "CI", name: "Cigna", sector: "Healthcare", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "SCHW", yahoo: "SCHW", name: "Charles Schwab", sector: "Financials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "SYK", yahoo: "SYK", name: "Stryker", sector: "Healthcare", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "ZTS", yahoo: "ZTS", name: "Zoetis", sector: "Healthcare", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "PFE", yahoo: "PFE", name: "Pfizer", sector: "Healthcare", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "MO", yahoo: "MO", name: "Altria Group", sector: "Consumer", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "BMY", yahoo: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "USB", yahoo: "USB", name: "U.S. Bancorp", sector: "Banking", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "TFC", yahoo: "TFC", name: "Truist Financial", sector: "Banking", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "FCX", yahoo: "FCX", name: "Freeport-McMoRan", sector: "Materials", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "ELV", yahoo: "ELV", name: "Elevance Health", sector: "Healthcare", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "DUK", yahoo: "DUK", name: "Duke Energy", sector: "Utilities", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "SO", yahoo: "SO", name: "Southern Company", sector: "Utilities", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "D", yahoo: "D", name: "Dominion Energy", sector: "Utilities", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "AEP", yahoo: "AEP", name: "American Electric Power", sector: "Utilities", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "PPL", yahoo: "PPL", name: "PPL Corp", sector: "Utilities", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "WEC", yahoo: "WEC", name: "WEC Energy", sector: "Utilities", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "AWK", yahoo: "AWK", name: "American Water Works", sector: "Utilities", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "OXY", yahoo: "OXY", name: "Occidental Petroleum", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "SLB", yahoo: "SLB", name: "Schlumberger", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "COP", yahoo: "COP", name: "ConocoPhillips", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "EOG", yahoo: "EOG", name: "EOG Resources", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "MPC", yahoo: "MPC", name: "Marathon Petroleum", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "PSX", yahoo: "PSX", name: "Phillips 66", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "VLO", yahoo: "VLO", name: "Valero Energy", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "HES", yahoo: "HES", name: "Hess Corp", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "PXD", yahoo: "PXD", name: "Pioneer Natural Resources", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "F", yahoo: "F", name: "Ford Motor", sector: "Auto", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "GM", yahoo: "GM", name: "General Motors", sector: "Auto", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "STLA", yahoo: "STLA", name: "Stellantis", sector: "Auto", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "HMC", yahoo: "HMC", name: "Honda Motor", sector: "Auto", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "TM", yahoo: "TM", name: "Toyota Motor", sector: "Auto", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "WDAY", yahoo: "WDAY", name: "Workday", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "PANW", yahoo: "PANW", name: "Palo Alto Networks", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "FTNT", yahoo: "FTNT", name: "Fortinet", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "MRVL", yahoo: "MRVL", name: "Marvell Technology", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "MU", yahoo: "MU", name: "Micron Technology", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "SNPS", yahoo: "SNPS", name: "Synopsys", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "CDNS", yahoo: "CDNS", name: "Cadence Design Systems", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "KLAC", yahoo: "KLAC", name: "KLA Corp", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "LRCX", yahoo: "LRCX", name: "Lam Research", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "AMAT", yahoo: "AMAT", name: "Applied Materials", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "ARM", yahoo: "ARM", name: "ARM Holdings", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "SMCI", yahoo: "SMCI", name: "Super Micro Computer", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "APP", yahoo: "APP", name: "AppLovin", sector: "Technology", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "CEG", yahoo: "CEG", name: "Constellation Energy", sector: "Utilities", market: "US", exchange: "NASDAQ", currency: "USD" },
  { symbol: "VST", yahoo: "VST", name: "Vistra", sector: "Utilities", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "OKE", yahoo: "OKE", name: "ONEOK", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "WMB", yahoo: "WMB", name: "Williams Companies", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "KMI", yahoo: "KMI", name: "Kinder Morgan", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "HAL", yahoo: "HAL", name: "Halliburton", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
  { symbol: "DVN", yahoo: "DVN", name: "Devon Energy", sector: "Energy", market: "US", exchange: "NYSE", currency: "USD" },
];

export const UNIVERSE: Instrument[] = [...INDIA_STOCKS, ...US_STOCKS];

export const INDICES = {
  IN: [
    { symbol: "NIFTY 50", yahoo: "^NSEI", name: "Nifty 50", market: "IN" as const },
    { symbol: "SENSEX", yahoo: "^BSESN", name: "BSE Sensex", market: "IN" as const },
    { symbol: "BANKNIFTY", yahoo: "^NSEBANK", name: "Nifty Bank", market: "IN" as const },
  ],
  US: [
    { symbol: "S&P 500", yahoo: "^GSPC", name: "S&P 500", market: "US" as const },
    { symbol: "DOW", yahoo: "^DJI", name: "Dow Jones", market: "US" as const },
    { symbol: "NASDAQ", yahoo: "^IXIC", name: "Nasdaq Composite", market: "US" as const },
    { symbol: "VIX", yahoo: "^VIX", name: "CBOE VIX", market: "US" as const },
  ],
};

export function catalog(): Instrument[] {
  return UNIVERSE;
}

export function findInCatalog(query: string): Instrument | null {
  const q = decodeURIComponent(query).trim().toUpperCase();
  return (
    UNIVERSE.find((s) => s.yahoo.toUpperCase() === q) ??
    UNIVERSE.find((s) => s.symbol.toUpperCase() === q) ??
    null
  );
}

export function classifyMarket(yahoo: string, exchange = ""): Market {
  const y = yahoo.toUpperCase();
  const ex = exchange.toUpperCase();
  if (y.endsWith(".NS") || y.endsWith(".BO") || ex.includes("NSE") || ex.includes("BSE") || ex.includes("NATIONAL STOCK")) {
    return "IN";
  }
  return "US";
}
