// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.36.0
// source: analytics/v1/analytics.proto

package analyticsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AnalyticsService_GetSignals_FullMethodName          = "/stockmafia.analytics.v1.AnalyticsService/GetSignals"
	AnalyticsService_GetAlgoConfig_FullMethodName       = "/stockmafia.analytics.v1.AnalyticsService/GetAlgoConfig"
	AnalyticsService_GenerateSuggestions_FullMethodName = "/stockmafia.analytics.v1.AnalyticsService/GenerateSuggestions"
	AnalyticsService_ExecuteSuggestion_FullMethodName   = "/stockmafia.analytics.v1.AnalyticsService/ExecuteSuggestion"
	AnalyticsService_RunScreener_FullMethodName         = "/stockmafia.analytics.v1.AnalyticsService/RunScreener"
	AnalyticsService_GetStrategies_FullMethodName       = "/stockmafia.analytics.v1.AnalyticsService/GetStrategies"
	AnalyticsService_RunStrategy_FullMethodName         = "/stockmafia.analytics.v1.AnalyticsService/RunStrategy"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetSignals(ctx context.Context, in *GetSignalsRequest, opts ...grpc.CallOption) (*GetSignalsResponse, error)
	GetAlgoConfig(ctx context.Context, in *GetAlgoConfigRequest, opts ...grpc.CallOption) (*GetAlgoConfigResponse, error)
	GenerateSuggestions(ctx context.Context, in *GenerateSuggestionsRequest, opts ...grpc.CallOption) (*GenerateSuggestionsResponse, error)
	ExecuteSuggestion(ctx context.Context, in *ExecuteSuggestionRequest, opts ...grpc.CallOption) (*ExecuteSuggestionResponse, error)
	RunScreener(ctx context.Context, in *RunScreenerRequest, opts ...grpc.CallOption) (*RunScreenerResponse, error)
	GetStrategies(ctx context.Context, in *GetStrategiesRequest, opts ...grpc.CallOption) (*GetStrategiesResponse, error)
	RunStrategy(ctx context.Context, in *RunStrategyRequest, opts ...grpc.CallOption) (*RunStrategyResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetSignals(ctx context.Context, in *GetSignalsRequest, opts ...grpc.CallOption) (*GetSignalsResponse, error) {
	out := new(GetSignalsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetSignals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetAlgoConfig(ctx context.Context, in *GetAlgoConfigRequest, opts ...grpc.CallOption) (*GetAlgoConfigResponse, error) {
	out := new(GetAlgoConfigResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetAlgoConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GenerateSuggestions(ctx context.Context, in *GenerateSuggestionsRequest, opts ...grpc.CallOption) (*GenerateSuggestionsResponse, error) {
	out := new(GenerateSuggestionsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GenerateSuggestions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) ExecuteSuggestion(ctx context.Context, in *ExecuteSuggestionRequest, opts ...grpc.CallOption) (*ExecuteSuggestionResponse, error) {
	out := new(ExecuteSuggestionResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_ExecuteSuggestion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) RunScreener(ctx context.Context, in *RunScreenerRequest, opts ...grpc.CallOption) (*RunScreenerResponse, error) {
	out := new(RunScreenerResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_RunScreener_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetStrategies(ctx context.Context, in *GetStrategiesRequest, opts ...grpc.CallOption) (*GetStrategiesResponse, error) {
	out := new(GetStrategiesResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetStrategies_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) RunStrategy(ctx context.Context, in *RunStrategyRequest, opts ...grpc.CallOption) (*RunStrategyResponse, error) {
	out := new(RunStrategyResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_RunStrategy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility
type AnalyticsServiceServer interface {
	GetSignals(context.Context, *GetSignalsRequest) (*GetSignalsResponse, error)
	GetAlgoConfig(context.Context, *GetAlgoConfigRequest) (*GetAlgoConfigResponse, error)
	GenerateSuggestions(context.Context, *GenerateSuggestionsRequest) (*GenerateSuggestionsResponse, error)
	ExecuteSuggestion(context.Context, *ExecuteSuggestionRequest) (*ExecuteSuggestionResponse, error)
	RunScreener(context.Context, *RunScreenerRequest) (*RunScreenerResponse, error)
	GetStrategies(context.Context, *GetStrategiesRequest) (*GetStrategiesResponse, error)
	RunStrategy(context.Context, *RunStrategyRequest) (*RunStrategyResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticsServiceServer struct {
}

func (UnimplementedAnalyticsServiceServer) GetSignals(context.Context, *GetSignalsRequest) (*GetSignalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignals not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetAlgoConfig(context.Context, *GetAlgoConfigRequest) (*GetAlgoConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlgoConfig not implemented")
}
func (UnimplementedAnalyticsServiceServer) GenerateSuggestions(context.Context, *GenerateSuggestionsRequest) (*GenerateSuggestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSuggestions not implemented")
}
func (UnimplementedAnalyticsServiceServer) ExecuteSuggestion(context.Context, *ExecuteSuggestionRequest) (*ExecuteSuggestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteSuggestion not implemented")
}
func (UnimplementedAnalyticsServiceServer) RunScreener(context.Context, *RunScreenerRequest) (*RunScreenerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunScreener not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetStrategies(context.Context, *GetStrategiesRequest) (*GetStrategiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrategies not implemented")
}
func (UnimplementedAnalyticsServiceServer) RunStrategy(context.Context, *RunStrategyRequest) (*RunStrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunStrategy not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetSignals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetSignals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetSignals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetSignals(ctx, req.(*GetSignalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetAlgoConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlgoConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetAlgoConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetAlgoConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetAlgoConfig(ctx, req.(*GetAlgoConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GenerateSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GenerateSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GenerateSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GenerateSuggestions(ctx, req.(*GenerateSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_ExecuteSuggestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSuggestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).ExecuteSuggestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_ExecuteSuggestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).ExecuteSuggestion(ctx, req.(*ExecuteSuggestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_RunScreener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunScreenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).RunScreener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_RunScreener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).RunScreener(ctx, req.(*RunScreenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetStrategies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetStrategies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetStrategies(ctx, req.(*GetStrategiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_RunStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).RunStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_RunStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).RunStrategy(ctx, req.(*RunStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stockmafia.analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSignals",
			Handler:    _AnalyticsService_GetSignals_Handler,
		},
		{
			MethodName: "GetAlgoConfig",
			Handler:    _AnalyticsService_GetAlgoConfig_Handler,
		},
		{
			MethodName: "GenerateSuggestions",
			Handler:    _AnalyticsService_GenerateSuggestions_Handler,
		},
		{
			MethodName: "ExecuteSuggestion",
			Handler:    _AnalyticsService_ExecuteSuggestion_Handler,
		},
		{
			MethodName: "RunScreener",
			Handler:    _AnalyticsService_RunScreener_Handler,
		},
		{
			MethodName: "GetStrategies",
			Handler:    _AnalyticsService_GetStrategies_Handler,
		},
		{
			MethodName: "RunStrategy",
			Handler:    _AnalyticsService_RunStrategy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics/v1/analytics.proto",
}
