// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.36.0
// source: price/v1/price.proto

package pricev1

import (
	v1 "github.com/stockmafia/trading-app/proto/stockmafia/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetQuotesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQuotesRequest) Reset() {
	*x = GetQuotesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_v1_price_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotesRequest) ProtoMessage() {}

func (x *GetQuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_price_v1_price_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotesRequest.ProtoReflect.Descriptor instead.
func (*GetQuotesRequest) Descriptor() ([]byte, []int) {
	return file_price_v1_price_proto_rawDescGZIP(), []int{0}
}

type GetQuotesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quotes []*v1.Quote `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
}

func (x *GetQuotesResponse) Reset() {
	*x = GetQuotesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_v1_price_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotesResponse) ProtoMessage() {}

func (x *GetQuotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_price_v1_price_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotesResponse.ProtoReflect.Descriptor instead.
func (*GetQuotesResponse) Descriptor() ([]byte, []int) {
	return file_price_v1_price_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuotesResponse) GetQuotes() []*v1.Quote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

type GetStockDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Yahoo string `protobuf:"bytes,1,opt,name=yahoo,proto3" json:"yahoo,omitempty"`
}

func (x *GetStockDetailRequest) Reset() {
	*x = GetStockDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_v1_price_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStockDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockDetailRequest) ProtoMessage() {}

func (x *GetStockDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_price_v1_price_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockDetailRequest.ProtoReflect.Descriptor instead.
func (*GetStockDetailRequest) Descriptor() ([]byte, []int) {
	return file_price_v1_price_proto_rawDescGZIP(), []int{2}
}

func (x *GetStockDetailRequest) GetYahoo() string {
	if x != nil {
		return x.Yahoo
	}
	return ""
}

type GetStockDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stock        *v1.Stock    `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	Quote        *v1.Quote    `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	Candles      []*v1.Candle `protobuf:"bytes,3,rep,name=candles,proto3" json:"candles,omitempty"`
	Fundamentals string       `protobuf:"bytes,4,opt,name=fundamentals,proto3" json:"fundamentals,omitempty"`
	News         string       `protobuf:"bytes,5,opt,name=news,proto3" json:"news,omitempty"`
}

func (x *GetStockDetailResponse) Reset() {
	*x = GetStockDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_v1_price_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStockDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockDetailResponse) ProtoMessage() {}

func (x *GetStockDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_price_v1_price_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockDetailResponse.ProtoReflect.Descriptor instead.
func (*GetStockDetailResponse) Descriptor() ([]byte, []int) {
	return file_price_v1_price_proto_rawDescGZIP(), []int{3}
}

func (x *GetStockDetailResponse) GetStock() *v1.Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

func (x *GetStockDetailResponse) GetQuote() *v1.Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *GetStockDetailResponse) GetCandles() []*v1.Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *GetStockDetailResponse) GetFundamentals() string {
	if x != nil {
		return x.Fundamentals
	}
	return ""
}

func (x *GetStockDetailResponse) GetNews() string {
	if x != nil {
		return x.News
	}
	return ""
}

var File_price_v1_price_proto protoreflect.FileDescriptor

var file_price_v1_price_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66,
	0x69, 0x61, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x15, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x71,
	0x75, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x06, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x73,
	0x22, 0x2d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x79, 0x61, 0x68,
	0x6f, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x79, 0x61, 0x68, 0x6f, 0x6f, 0x22,
	0xee, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x31, 0x0a,
	0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65,
	0x12, 0x36, 0x0a, 0x07, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52,
	0x07, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x75, 0x6e, 0x64,
	0x61, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x66, 0x75, 0x6e, 0x64, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x65, 0x77, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x65, 0x77, 0x73,
	0x32, 0xd5, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x5a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x25,
	0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66,
	0x69, 0x61, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x69, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12,
	0x2a, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69,
	0x61, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_price_v1_price_proto_rawDescOnce sync.Once
	file_price_v1_price_proto_rawDescData = file_price_v1_price_proto_rawDesc
)

func file_price_v1_price_proto_rawDescGZIP() []byte {
	file_price_v1_price_proto_rawDescOnce.Do(func() {
		file_price_v1_price_proto_rawDescData = protoimpl.X.CompressGZIP(file_price_v1_price_proto_rawDescData)
	})
	return file_price_v1_price_proto_rawDescData
}

var file_price_v1_price_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_price_v1_price_proto_goTypes = []interface{}{
	(*GetQuotesRequest)(nil),       // 0: stockmafia.price.v1.GetQuotesRequest
	(*GetQuotesResponse)(nil),      // 1: stockmafia.price.v1.GetQuotesResponse
	(*GetStockDetailRequest)(nil),  // 2: stockmafia.price.v1.GetStockDetailRequest
	(*GetStockDetailResponse)(nil), // 3: stockmafia.price.v1.GetStockDetailResponse
	(*v1.Quote)(nil),               // 4: stockmafia.common.v1.Quote
	(*v1.Stock)(nil),               // 5: stockmafia.common.v1.Stock
	(*v1.Candle)(nil),              // 6: stockmafia.common.v1.Candle
}
var file_price_v1_price_proto_depIdxs = []int32{
	4, // 0: stockmafia.price.v1.GetQuotesResponse.quotes:type_name -> stockmafia.common.v1.Quote
	5, // 1: stockmafia.price.v1.GetStockDetailResponse.stock:type_name -> stockmafia.common.v1.Stock
	4, // 2: stockmafia.price.v1.GetStockDetailResponse.quote:type_name -> stockmafia.common.v1.Quote
	6, // 3: stockmafia.price.v1.GetStockDetailResponse.candles:type_name -> stockmafia.common.v1.Candle
	0, // 4: stockmafia.price.v1.PriceService.GetQuotes:input_type -> stockmafia.price.v1.GetQuotesRequest
	2, // 5: stockmafia.price.v1.PriceService.GetStockDetail:input_type -> stockmafia.price.v1.GetStockDetailRequest
	1, // 6: stockmafia.price.v1.PriceService.GetQuotes:output_type -> stockmafia.price.v1.GetQuotesResponse
	3, // 7: stockmafia.price.v1.PriceService.GetStockDetail:output_type -> stockmafia.price.v1.GetStockDetailResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_price_v1_price_proto_init() }
func file_price_v1_price_proto_init() {
	if File_price_v1_price_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_price_v1_price_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_v1_price_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_v1_price_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStockDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_v1_price_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStockDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_price_v1_price_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_price_v1_price_proto_goTypes,
		DependencyIndexes: file_price_v1_price_proto_depIdxs,
		MessageInfos:      file_price_v1_price_proto_msgTypes,
	}.Build()
	File_price_v1_price_proto = out.File
	file_price_v1_price_proto_rawDesc = nil
	file_price_v1_price_proto_goTypes = nil
	file_price_v1_price_proto_depIdxs = nil
}
