// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.36.0
// source: crawler/v1/crawler.proto

package crawlerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CrawlerService_GetCrawlStatus_FullMethodName = "/stockmafia.crawler.v1.CrawlerService/GetCrawlStatus"
	CrawlerService_StartCrawl_FullMethodName     = "/stockmafia.crawler.v1.CrawlerService/StartCrawl"
	CrawlerService_CrawlSymbol_FullMethodName    = "/stockmafia.crawler.v1.CrawlerService/CrawlSymbol"
	CrawlerService_TriggerCrawl_FullMethodName   = "/stockmafia.crawler.v1.CrawlerService/TriggerCrawl"
	CrawlerService_GetStocks_FullMethodName      = "/stockmafia.crawler.v1.CrawlerService/GetStocks"
	CrawlerService_GetStock_FullMethodName       = "/stockmafia.crawler.v1.CrawlerService/GetStock"
	CrawlerService_GetCandles_FullMethodName     = "/stockmafia.crawler.v1.CrawlerService/GetCandles"
	CrawlerService_GetQuote_FullMethodName       = "/stockmafia.crawler.v1.CrawlerService/GetQuote"
	CrawlerService_GetQuotes_FullMethodName      = "/stockmafia.crawler.v1.CrawlerService/GetQuotes"
)

// CrawlerServiceClient is the client API for CrawlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrawlerServiceClient interface {
	GetCrawlStatus(ctx context.Context, in *CrawlStatusRequest, opts ...grpc.CallOption) (*CrawlStatusResponse, error)
	StartCrawl(ctx context.Context, in *StartCrawlRequest, opts ...grpc.CallOption) (*StartCrawlResponse, error)
	CrawlSymbol(ctx context.Context, in *CrawlSymbolRequest, opts ...grpc.CallOption) (*CrawlSymbolResponse, error)
	TriggerCrawl(ctx context.Context, in *TriggerCrawlRequest, opts ...grpc.CallOption) (*TriggerCrawlResponse, error)
	GetStocks(ctx context.Context, in *GetStocksRequest, opts ...grpc.CallOption) (*GetStocksResponse, error)
	GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error)
	GetCandles(ctx context.Context, in *GetCandlesRequest, opts ...grpc.CallOption) (*GetCandlesResponse, error)
	GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error)
	GetQuotes(ctx context.Context, in *GetQuotesRequest, opts ...grpc.CallOption) (*GetQuotesResponse, error)
}

type crawlerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrawlerServiceClient(cc grpc.ClientConnInterface) CrawlerServiceClient {
	return &crawlerServiceClient{cc}
}

func (c *crawlerServiceClient) GetCrawlStatus(ctx context.Context, in *CrawlStatusRequest, opts ...grpc.CallOption) (*CrawlStatusResponse, error) {
	out := new(CrawlStatusResponse)
	err := c.cc.Invoke(ctx, CrawlerService_GetCrawlStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) StartCrawl(ctx context.Context, in *StartCrawlRequest, opts ...grpc.CallOption) (*StartCrawlResponse, error) {
	out := new(StartCrawlResponse)
	err := c.cc.Invoke(ctx, CrawlerService_StartCrawl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) CrawlSymbol(ctx context.Context, in *CrawlSymbolRequest, opts ...grpc.CallOption) (*CrawlSymbolResponse, error) {
	out := new(CrawlSymbolResponse)
	err := c.cc.Invoke(ctx, CrawlerService_CrawlSymbol_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) TriggerCrawl(ctx context.Context, in *TriggerCrawlRequest, opts ...grpc.CallOption) (*TriggerCrawlResponse, error) {
	out := new(TriggerCrawlResponse)
	err := c.cc.Invoke(ctx, CrawlerService_TriggerCrawl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) GetStocks(ctx context.Context, in *GetStocksRequest, opts ...grpc.CallOption) (*GetStocksResponse, error) {
	out := new(GetStocksResponse)
	err := c.cc.Invoke(ctx, CrawlerService_GetStocks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error) {
	out := new(GetStockResponse)
	err := c.cc.Invoke(ctx, CrawlerService_GetStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) GetCandles(ctx context.Context, in *GetCandlesRequest, opts ...grpc.CallOption) (*GetCandlesResponse, error) {
	out := new(GetCandlesResponse)
	err := c.cc.Invoke(ctx, CrawlerService_GetCandles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error) {
	out := new(GetQuoteResponse)
	err := c.cc.Invoke(ctx, CrawlerService_GetQuote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) GetQuotes(ctx context.Context, in *GetQuotesRequest, opts ...grpc.CallOption) (*GetQuotesResponse, error) {
	out := new(GetQuotesResponse)
	err := c.cc.Invoke(ctx, CrawlerService_GetQuotes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlerServiceServer is the server API for CrawlerService service.
// All implementations must embed UnimplementedCrawlerServiceServer
// for forward compatibility
type CrawlerServiceServer interface {
	GetCrawlStatus(context.Context, *CrawlStatusRequest) (*CrawlStatusResponse, error)
	StartCrawl(context.Context, *StartCrawlRequest) (*StartCrawlResponse, error)
	CrawlSymbol(context.Context, *CrawlSymbolRequest) (*CrawlSymbolResponse, error)
	TriggerCrawl(context.Context, *TriggerCrawlRequest) (*TriggerCrawlResponse, error)
	GetStocks(context.Context, *GetStocksRequest) (*GetStocksResponse, error)
	GetStock(context.Context, *GetStockRequest) (*GetStockResponse, error)
	GetCandles(context.Context, *GetCandlesRequest) (*GetCandlesResponse, error)
	GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error)
	GetQuotes(context.Context, *GetQuotesRequest) (*GetQuotesResponse, error)
	mustEmbedUnimplementedCrawlerServiceServer()
}

// UnimplementedCrawlerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCrawlerServiceServer struct {
}

func (UnimplementedCrawlerServiceServer) GetCrawlStatus(context.Context, *CrawlStatusRequest) (*CrawlStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCrawlStatus not implemented")
}
func (UnimplementedCrawlerServiceServer) StartCrawl(context.Context, *StartCrawlRequest) (*StartCrawlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCrawl not implemented")
}
func (UnimplementedCrawlerServiceServer) CrawlSymbol(context.Context, *CrawlSymbolRequest) (*CrawlSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrawlSymbol not implemented")
}
func (UnimplementedCrawlerServiceServer) TriggerCrawl(context.Context, *TriggerCrawlRequest) (*TriggerCrawlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerCrawl not implemented")
}
func (UnimplementedCrawlerServiceServer) GetStocks(context.Context, *GetStocksRequest) (*GetStocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStocks not implemented")
}
func (UnimplementedCrawlerServiceServer) GetStock(context.Context, *GetStockRequest) (*GetStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStock not implemented")
}
func (UnimplementedCrawlerServiceServer) GetCandles(context.Context, *GetCandlesRequest) (*GetCandlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCandles not implemented")
}
func (UnimplementedCrawlerServiceServer) GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedCrawlerServiceServer) GetQuotes(context.Context, *GetQuotesRequest) (*GetQuotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuotes not implemented")
}
func (UnimplementedCrawlerServiceServer) mustEmbedUnimplementedCrawlerServiceServer() {}

// UnsafeCrawlerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrawlerServiceServer will
// result in compilation errors.
type UnsafeCrawlerServiceServer interface {
	mustEmbedUnimplementedCrawlerServiceServer()
}

func RegisterCrawlerServiceServer(s grpc.ServiceRegistrar, srv CrawlerServiceServer) {
	s.RegisterService(&CrawlerService_ServiceDesc, srv)
}

func _CrawlerService_GetCrawlStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).GetCrawlStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_GetCrawlStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).GetCrawlStatus(ctx, req.(*CrawlStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_StartCrawl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCrawlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).StartCrawl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_StartCrawl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).StartCrawl(ctx, req.(*StartCrawlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_CrawlSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).CrawlSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_CrawlSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).CrawlSymbol(ctx, req.(*CrawlSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_TriggerCrawl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerCrawlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).TriggerCrawl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_TriggerCrawl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).TriggerCrawl(ctx, req.(*TriggerCrawlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_GetStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).GetStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_GetStocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).GetStocks(ctx, req.(*GetStocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_GetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).GetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_GetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).GetStock(ctx, req.(*GetStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_GetCandles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).GetCandles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_GetCandles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).GetCandles(ctx, req.(*GetCandlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_GetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).GetQuote(ctx, req.(*GetQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_GetQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).GetQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_GetQuotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).GetQuotes(ctx, req.(*GetQuotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrawlerService_ServiceDesc is the grpc.ServiceDesc for CrawlerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrawlerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stockmafia.crawler.v1.CrawlerService",
	HandlerType: (*CrawlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCrawlStatus",
			Handler:    _CrawlerService_GetCrawlStatus_Handler,
		},
		{
			MethodName: "StartCrawl",
			Handler:    _CrawlerService_StartCrawl_Handler,
		},
		{
			MethodName: "CrawlSymbol",
			Handler:    _CrawlerService_CrawlSymbol_Handler,
		},
		{
			MethodName: "TriggerCrawl",
			Handler:    _CrawlerService_TriggerCrawl_Handler,
		},
		{
			MethodName: "GetStocks",
			Handler:    _CrawlerService_GetStocks_Handler,
		},
		{
			MethodName: "GetStock",
			Handler:    _CrawlerService_GetStock_Handler,
		},
		{
			MethodName: "GetCandles",
			Handler:    _CrawlerService_GetCandles_Handler,
		},
		{
			MethodName: "GetQuote",
			Handler:    _CrawlerService_GetQuote_Handler,
		},
		{
			MethodName: "GetQuotes",
			Handler:    _CrawlerService_GetQuotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crawler/v1/crawler.proto",
}
