input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [service] == "gateway" {
    mutate {
      add_field => { "[@metadata][index]" => "gateway-logs" }
    }
  } else if [service] == "crawler-service" {
    mutate {
      add_field => { "[@metadata][index]" => "crawler-logs" }
    }
  } else if [service] == "price-service" {
    mutate {
      add_field => { "[@metadata][index]" => "price-logs" }
    }
  } else if [service] == "analytics-service" {
    mutate {
      add_field => { "[@metadata][index]" => "analytics-logs" }
    }
  } else if [service] == "alert-service" {
    mutate {
      add_field => { "[@metadata][index]" => "alert-logs" }
    }
  } else if [service] == "portfolio-service" {
    mutate {
      add_field => { "[@metadata][index]" => "portfolio-logs" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][index]" => "other-logs" }
    }
  }

  date {
    match => [ "timestamp", "ISO8601" ]
    target => "@timestamp"
  }

  mutate {
    remove_field => ["timestamp"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }
}
